version: '3.8'

networks:
  network:
   driver: bridge

volumes:
  postgres_data:
  postgres_data2:

services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "443:443"
    networks:
      - network
    depends_on:
      - api
      - mdb

  api:
    build:
      context: .
      dockerfile: MonosortMiniApp.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5075
    ports:
      - '5075:5075'
    depends_on:
      - db
    networks:
      - network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  md:
    build:
      context: .
      dockerfile: Form/Form.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5076
    ports:
      - '5076:5076'
    depends_on:
      - mdb
    networks:
      - network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  mdb:
    image: postgres:latest
    container_name: mdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2208
      POSTGRES_DB: Form
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - network

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2208
      POSTGRES_DB: MonosortMiniApp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network