version: '3.8'

networks:
  mono:
   external: true
   name: mono

volumes:
  postgres_data:
  postgres_data2:

services:

  api:
    build:
      context: .
      dockerfile: MonosortMiniApp.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5075
    ports:
      - '5075:5075'
    depends_on:
      - db
    networks:
      - mono
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2208
      POSTGRES_DB: MonosortMiniApp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    
      - mono