version: '3.8'

networks:
  mono:
   external: true
   name: mono

volumes:
  postgres_data:
  postgres_data2:

services:

  api:
    build:
      context: .
      dockerfile: MonosortMiniApp.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5075
      - DB_CONNECTION_STRING
      - JWT_ISSUER
      - JWT_KEY
      - RABBIT_HOST_NAME
      - RABBIT_USER_NAME
      - RABBIT_PASSWORD
      - RABBIT_PORT
    ports:
      - '5075:5075'
    depends_on:
      - db
    networks:
      - mono
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP порт
      - "15672:15672"  # Web UI
    networks:
      - mono
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "2208"

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2208
      POSTGRES_DB: MonosortMiniApp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mono